# Generated by Django 4.2 on 2024-09-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparrel',
            name='nombreRef',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aparrel',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
