# Generated by Django 4.2 on 2024-09-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0002_aparrel_nombreref_alter_aparrel_referencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparrel',
            old_name='nombreRef',
            new_name='nombre',
        ),
    ]
