# Generated by Django 4.2 on 2024-09-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0003_rename_nombreref_aparrel_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparrel',
            old_name='nombre',
            new_name='nombreref',
        ),
    ]
