# Generated by Django 4.2 on 2024-09-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0004_rename_nombre_aparrel_nombreref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparrel',
            old_name='nombreref',
            new_name='nombre',
        ),
    ]
