# Generated by Django 4.2 on 2024-09-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0005_rename_nombreref_aparrel_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparrel',
            old_name='nombre',
            new_name='codigoSapMD',
        ),
        migrations.AddField(
            model_name='aparrel',
            name='codigoSapPT',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aparrel',
            name='descripcionColor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aparrel',
            name='fotoReferencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aparrel',
            name='nombreSistema',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
