# Generated by Django 4.2 on 2024-09-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparrel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=30, null=True)),
                ('fotoReferencia', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSapMD', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSapPT', models.CharField(blank=True, max_length=30, null=True)),
                ('nombreSistema', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcionColor', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
