# Generated by Django 4.2 on 2024-10-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
    ]
