# Generated by Django 4.2 on 2024-09-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='jefer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
