# Generated by Django 4.2 on 2024-10-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
