# Generated by Django 4.2 on 2024-09-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0002_proyecto_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='proyecto',
            new_name='proyecto_id',
        ),
    ]
