# Generated by Django 4.2 on 2024-09-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0002_task_jefer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='jefer',
        ),
    ]
