# Generated by Django 4.2 on 2024-09-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0004_rename_proyecto_id_tasks_proyecto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
